name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Встановлення JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Збірка Maven
      run: mvn clean install
